### ISSUE TITLE
ack

### ISSUE THREAD

**Issue by 124642027** [phachon/wmqx#1]
https://github.com/phachon/wmqx/blob/master/container/worker.go

for {
			select {
			case d := <-delivery:
				if len(d.Body) == 0 {
					app.Log.Error("Consumer " + processMessage.Key + " receive message body is null")
					**### d.Ack(false)**
					continue
				}
  ...........
}

请帮忙看下，如果delivery收到的body是空，那么ack之后，amqp会抛异常，这个delivery的body会一直未空

https://www.rabbitmq.com/confirms.html#acknowledgement-modes

Should a client acknowledge the same delivery tag more than once, RabbitMQ will result a channel error such as PRECONDITION_FAILED - unknown delivery tag 100. The same channel exception will be thrown if an unknown delivery tag is used.

**Comment by phachon** [comment]
@lisbitid body 理论上是不可能为空的，贴一下具体的 panic 信息

**Comment by 124642027** [comment]
> @lisbitid body 理论上是不可能为空的，贴一下具体的 panic 信息

问题就是，没有报错信息，
我这边看到的现象是delivery的body一直收到的数据是空，然后过一会队列的消费者就会在rabbitmq的后台里面查看不到了，但是这个worker的go groutine还在，因为一直在打印receive message body is null
我这边打印了worker中使用的channel和delivery，连接属性都是nil了

或者咱们这边有遇到过这种现象吗？

**Comment by 124642027** [comment]
@phachon 这边大概复现了问题，我们这边有在压测mq的服务，消费者手动ack，ack的qps到10000左右时，出现了一段时间消息不能ack成功的情况。这时候，consumer的delivery接到的消息的body就是null了
咱们代码的逻辑没问题
